version: '3.1'

services:

  mysql:
    container_name: goec-mysql
    image: mysql:8.0
    ports:
    - "3313:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goecdb
    volumes:
    - ./.data/mysql:/var/lib/mysql
